### ISSUE TITLE
Allows Kontax to process photo from camera library too

### ISSUE THREAD

**Issue by kxvn-lx** [kxvn-lx/Kontax-Cam#5]
This would be an option under the lab, where user can import photo instead. Will be processed with the selected effects and filter.

**Comment by dumblob** [comment]
I suppose this feature was implemented. Does this feature also save the edited picture back to the `Camera` app? If not, could this be implemented?

**Comment by kxvn-lx** [comment]
Currently this feature is not yet implemented, the edited photo is saved back to the Camera app as a new photo. Perhaps someone could help out with this
